### PR TITLE
feat: use ast to parse doc more quickly

### LINKED ISSUE #73: Problem with pug extend
Warning: Cannot parse components/*.vue: TypeError: A child of Block (Pug:2) is of type Extends, which is not supported by pug-code-gen. Please use pug-linker to preprocess this AST.

It usually means that vue-docgen-api does not understand your source code or when using third-party libraries

### PR DESCRIPTION
**Pull request by elevatebart**
It would be amazing to avoid execution issues when looking at documentation. 
Plus, no execution means better performance. Abstract Syntax Tree (ast) are a way to parse code without evalualting or even comiling it.

New algorythm
1. get the **script block** and **template block** from the **Single File Component** (SFC) using vue-template-compiler.parse
1. get the **AST** from this **script block** using `recast` and `@babel/parser`
1. get the **exported subtree** of this **AST** which will contain the documented component
1. get the **displayName**, **props** and **methods** from this **AST** (to get types, default and parameter names) 
1. get the **docblocks** out of the **script block** or the **AST**
1. merge the **docblocks** with the **props** and **mehods**
1. add the **slots** documentations to the documentation object

- [x] General Scaffolding
- [x] Props Handler
- [x] Methods and params Handler
- [x] Component description, name and comment Handler (extra tags to be handled)
- [x] Slots Handler
- [x] Mixins Handler
- [x] Events handler
- [x] `extends` property of a component (implement like a mixin)
- [x] jsx parser
- [x] typescript parser
- [x] get rid of the `react-docgen` dependency (only on `resolveToValue`)
- [x] make it all typescript
- [x] deal with require mixins and extends
- [x] use typescritpt parsing to determine type of arguments
- [x] enable parsing of Decorated class type components `vue-property-decorator`

fixes #73, #58, #53, #50, #44, #33, #27, #25, #23, #11, #9 

[BREAKING CHANGE]: `comment` properties (containing the full extract of each leading comment (with all the `/**` and the ` * `) are entirely removed from the documentation as they were not useful. Use `description` or `tags` instead.

[BREAKING CHANGE]: Events that are not commented near their call will not anymore be parsed. If you want to document events, do it as a leading comment of your event call

### CODE REVIEW

**Comment by elevatebart** [comment]
Need to fix the @public tag

**Comment by JessicaSachs** [comment]
I tried this branch out with a project that has vue-class-properties and JS and I'm unable to get it working. :-(

**Comment by elevatebart** [comment]
How did you install it ?

The only way to try it out through npm link here is how

1. Clone the repo on your computer through git
2. Npm ci
3. npm run compile
4. Npm link
5. In the project where you want to install it and install vue-docgen-api normally
6. In the same folder do npm link vue-docgen-api

Hope this helps,

If not, would you please share the error that you get? And provide a component that is failing?
Thank you ;)

Bart Ledoux
Twitter: @bartledoux
Github: @elevatebart

**Comment by JessicaSachs** [comment]
(I just gave 3.0.0 a go and posted results in Issue #9)

**Comment by therealpecus** [comment]
just poppin' in for a huge thanks to @elevatebart 
awesome job here!

**Pull request merged**
